### ISSUE TITLE
v0.11.0 checklist

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#202]
- [x] implement Foldable for Either (#119)
  - [x] remove `.skip`s from #192 and merge pull request
  - [x] implement Traversable for Either (#120)
  - [x] merge #207
  - [x] add `S.prepend` (#197)
  - [x] allow a user to bring her own environment (#188)
  - [x] upgrade to `sanctuary-def@0.6.x` (#217)
  - [x] add `S.keys`, `S.values` and `S.pairs` (#214)
  - [x] add `S.trim` (#176)
  - [x] remove [`replace(/plaid(?=[/]sanctuary)/g, 'sanctuary-js')`][1] (sanctuary-js/sanctuary-site#9)
  - [x] update website
  - [x] post upgrade guide (#227)

[1]: https://github.com/sanctuary-js/sanctuary-site/pull/7/files#r61008641

**Comment by davidchambers** [comment]
If I've missed anything you'd like to see included in the next release, please comment. :)

**Comment by Avaq** [comment]
Don't forget to write an upgrade guide! :)

**Comment by davidchambers** [comment]
Good point, @Avaq. Added. :)

**Comment by svozza** [comment]
I'd like to get `S.keys` and friends into this release, if possible.

**Comment by davidchambers** [comment]
Sounds good, Stefano. I've added it to the checklist. :)
