### ISSUE TITLE
v0.12.0 checklist

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#255]
- [x] expand documentation of type signatures and fix inconsistencies (#259)
- [x] list: remove ArrayLike type class (#263)
- [x] list: make the List type constructor simpler and more restrictive (#264)
- [x] merge sanctuary-js/sanctuary-def#82
- [x] merge sanctuary-js/sanctuary-site#13
- [x] complete, review, and merge sanctuary-js/sanctuary-type-classes#2
- [x] publish `sanctuary-type-classes@0.1.0`
- [x] publish sanctuary-type-classes to Bower registry (sanctuary-js/sanctuary-type-classes#4)
- [x] update sanctuary-def to depend on sanctuary-type-classes (sanctuary-js/sanctuary-def#83)
- [x] publish `sanctuary-def@0.7.0`
- [x] string, array: add `S.splitOn` and `S.joinWith` (#256)
- [x] maybe: add `S.fromMaybe_` (#316)
- [x] object: add `S.props` (#310)
- [x] test: check conformance to Fantasy Land laws with JSVerify (#305)
- [x] either: implement Bifunctor (#240)
- [x] merge sanctuary-js/sanctuary-type-identifiers#1
- [x] publish `sanctuary-type-identifiers@1.0.0`
- [x] merge sanctuary-js/sanctuary-type-classes#22
- [x] merge sanctuary-js/sanctuary-type-classes#24
- [x] publish `sanctuary-type-classes@2.0.0`
- [x] merge sanctuary-js/sanctuary-def#99
- [x] publish `sanctuary-def@0.8.0`
- [x] upgrade to `sanctuary-def@0.8.0` (#232)
- [x] regexp: revise `S.match` and add `S.matchAll` (#283)
- [x] merge sanctuary-js/sanctuary-def#112
- [x] publish `sanctuary-def@0.9.0`
- [x] upgrade to `sanctuary-def@0.9.0`
- [x] move `@@type` properties to type representatives (#312)
- [x] change type validators to use predicates rather than type representatives (#191)
- [x] add Fantasy Land functions (#216)
- [x] mention Fantasy Land in readme (#252)
- [x] update website to latest versions (sanctuary-js/sanctuary-site#14)
- [x] post upgrade guide

**Comment by davidchambers** [comment]
My goal is to publish v0.12.0 by the end of the year. Specifically no later than <time>2016-12-31T23:59:59.999+13:00</time>, giving me more than 1.6 billion milliseconds to make it happen:

```javascript
> new Date('2016-12-31T23:59:59.999+13:00').valueOf() - Date.now()
1609079887
```

If you're excited by the prospect of a year-end release, react to this comment to encourage me. :)

**Comment by davidchambers** [comment]
Three days to go; three big pull requests still to merge. It's possible!

**Comment by davidchambers** [comment]
Well, I didn't hit my self-imposed deadline, but we're close! It'll take a few days to review, tweak, and merge the remaining pull requests, and a day or two to update the website. I'll be in New Zealand for another ten days, and I'm not sure how much time I'll devote to Sanctuary. We'll definitely get v0.12.0 out at some point in January. :)

**Comment by safareli** [comment]
btw managing this PRs would be nicly done using `Projects` instead of this checklist, we could have  lists: `Todo, Doing, In Review, Merged` for example.

**Comment by davidchambers** [comment]
> btw managing this PRs would be nicly done using `Projects` instead of this checklist, we could have  lists: `Todo, Doing, In Review, Merged` for example.

I'm willing to give this a try.

I do like text files, though. What I'd like is a format that allows us to express dependencies between items on the list. For example:

    +--o  merge sanctuary-js/sanctuary-type-classes#22
    |
    +--o  merge sanctuary-js/sanctuary-type-classes#24
    |
    +-----o  publish sanctuary-type-classes@2.0.0

    +--o  merge sanctuary-js/sanctuary-def#99
    |
    +-----o  publish sanctuary-def@0.8.0
