### ISSUE TITLE
Big list of dependency-structure related improvements

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary#471]
I found myself getting lost in all of the ideas about how the `def` API and dependency structure could change to account for many of the small problems encountered by the community. So here's a list:

- [ ] sanctuary-js/sanctuary-def#74 Partial application of `def` to the `env`
- [ ] sanctuary-js/sanctuary-def#74 Merging with bilby for ad-hoc polymorphism
- [ ] https://github.com/sanctuary-js/sanctuary-def/issues/74#issuecomment-245125795; https://github.com/sanctuary-js/sanctuary/issues/246#issuecomment-244082029; https://github.com/sanctuary-js/sanctuary/issues/327#issuecomment-277448638; https://github.com/sanctuary-js/sanctuary/issues/335#issuecomment-279780194 Waiting for `def` rather than `env`
- [ ] https://github.com/sanctuary-js/sanctuary/issues/327#issuecomment-277986551; https://github.com/sanctuary-js/sanctuary/issues/262#issuecomment-352298307 Splitting the library and sharing `sanctuary-def` as a peer dependency
- [ ] https://github.com/sanctuary-js/sanctuary/issues/262#issuecomment-272823137 Simplification of `S.create`
- [ ] https://github.com/sanctuary-js/sanctuary-def/issues/137 Function namespaces
- [ ] https://github.com/sanctuary-js/sanctuary-def/issues/180 Allow for `def` to decorate an increased variety of functions
- [ ] https://github.com/sanctuary-js/sanctuary-def/issues/180#issuecomment-354196203 Unification of `def` and `$Function`

---

> If you have write access, feel free to append anything I might have missed to this list. Otherwise, put it in a comment and I'll amend the list myself. Please don't use the comments to share any new ideas - feel free to open issue for them and I will reference them here.

**Comment by davidchambers** [comment]
Thank you for compiling this list, Aldwin. :)
