### ISSUE TITLE
v0.15.0 checklist

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#535]
### Pre release

  - [x] update documentation to address #526
  - [ ] create migration script to transform `S.<name>(x, y)` into `S.<name>(x)(y)`
  - [x] merge sanctuary-js/sanctuary-type-classes#103
    - [x] publish `sanctuary-type-classes@8.2.1`
      - [x] merge sanctuary-js/sanctuary-type-classes#101
        - [x] publish `sanctuary-type-classes@9.0.0`
          - [x] upgrade all Sanctuary projects to `sanctuary-type-classes@9.0.0`
          - [x] upgrade davidchambers/doctest to `sanctuary-type-classes@9.0.0`
            - [x] publish `doctest@0.15.0`
              - [x] upgrade to `doctest@0.15.0`
                - [x] publish `sanctuary-scripts@1.6.0`
                  - [x] upgrade all Sanctuary projects to `sanctuary-scripts@1.6.0` ↩︎
  - [x] publish `sanctuary-identity@1.0.0`
    - [x] publish `sanctuary-either@1.0.0`
      - [x] publish `sanctuary-maybe@1.0.0`
        - [x] update Sanctuary to depend on sanctuary-either and sanctuary-maybe
          - [x] update and merge #377

### Post release

  - [x] publish release notes
  - [x] update website
  - [x] update [Ramda to Sanctuary][1]
  - [x] update the :goat:

[1]: https://github.com/sanctuary-js/sanctuary/wiki/Ramda-to-Sanctuary
